baseurl = "https://hbs-rcs.github.io/R_Intro-gapminder/"
relativeurls = true
languageCode = "en-us"
title = "R for the Social Sciences"
theme = "hugo-material-docs"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"

    logo = "fig/Rlogo.svg"

# menu items
[[menu.main]]
	name   = "Overview"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Before we start"
	url    = "before-we-start/"
	weight = 10

[[menu.main]]
	name   = "Intro to R"
	url    = "intro-to-r/"
	weight = 20

[[menu.main]]
	name   = "Data Frames"
	url    = "data-frames/"
	weight = 30

[[menu.main]]
	name   = "Exploring Data"
	url    = "exploring-your-data/"
	weight = 40

[[menu.main]]
	name   = "dplyr"
	url    = "dplyr/"
	weight = 50

[[menu.main]]
	name   = "Data Visualization"
	url    = "data-visualization/"
	weight = 60
