baseurl = "https://hbs-rcs.github.io/R_Intro-gapminder/"
canonifyURLs = false
languageCode = "en-us"
title = "R for the Social Sciences"
theme = "hugo-material-docs"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"

    logo = "images/logo.png"
    permalink = "#"

# menu items
[[menu.main]]
	name   = "Introduction"
	url    = ""
	weight = 1

[[menu.main]]
	name   = "RStudio IDE"
	url    = "rstudio-ide/"
	weight = 10

[[menu.main]]
	name   = "Data Import"
	url    = "data-import/"
	weight = 20

[[menu.main]]
	name   = "Data Transformation"
	url    = "data-transformation/"
	weight = 30

[[menu.main]]
	name   = "Data Visualization"
	url    = "data-visualization/"
	weight = 40

[[menu.main]]
	name   = "Base R"
	url    = "base-r/"
	weight = 50


[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
