---
title: R for the Social Sciences
---

Data Carpentry's aim is to teach researchers basic concepts, skills,
and tools for working more effectively with data. The lessons below
were designed for those interested in working with data in R.

Content Contributors: 

*   Bob Freeman
*   Kate Hertweck
*   Andrew Marder
*   Susan McClatchey
*   Tracy Teal
*   Ryan Williams

## Lessons

0. [Before we start](00-before-we-start.html)
1. [Introduction to R](01-intro-to-R.html)
2. [Starting with data](02-starting-with-data.html)
3. [Introduction to data frames](03-data-frames.html)
4. [Aggregating and analyzing data with dplyr](04-dplyr.html)
5. [Data visualization with ggplot2](05-data-visualization.html)

## Requirements

Data Carpentry's teaching is hands-on, so participants are encouraged
to use their own computers to ensure the proper setup of tools for an
efficient workflow.  *These lessons assume no prior knowledge of the
skills or tools*, but working through this lesson requires working
copies of the software described below.  To most effectively use these
materials, please make sure to install everything *before* working
through this lesson.

1. Install [R](https://www.r-project.org/).
2. Install [RStudio Desktop](https://www.rstudio.com/products/rstudio/download2/#download).
